### PR TITLE
Fix black outline on focus

### PR DESCRIPTION
**Pull request by itsmingjie**
image

### CODE REVIEW

**Comment by lachlanjc** [comment]
I haven’t tested this, but does the PR ensure there’s still a noticeable outline for keyboard users?

**Comment by itsmingjie** [comment]
@lachlanjc now this should be better. There won't be a square box, but there'll be a visible blue shadow when highlighted.

**Comment by sampoder** [comment]
thank you @itsmingjie!

**Comment by lachlanjc** [comment]
Beautiful, thanks!

**Pull request merged**
