### PR TITLE
Temporary Fix to Scrapbook

### PR DESCRIPTION
**Pull request by sampoder**
It isn't really a fix, simple a place holder

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/**](https://summer-git-hide-scrapbook-temp.hackclub.dev/) |
|:-:|
|<a href="https://summer-git-hide-scrapbook-temp.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/XtzBhg_WyaImaQppmpeul_wNVq0_.png">(view full size)</a> |







Commit e6d54f52230363bd41766f5d0008bc0b7cc4d303 (https://summer-git-hide-scrapbook-temp.hackclub.dev).

**Comment by sampoder** [comment]
hi Lachlan, or is this a bot?

**Comment by sampoder** [comment]
Merging

**Comment by lachlanjc** [comment]
This is a bot I don’t remember setting up :joy: anyway, fixed in #29, there was a one-character typo breaking it

**Pull request merged**
