### PR TITLE
Fixed that logo shit

### PR DESCRIPTION
**Pull request by iamcpdev**

### CODE REVIEW

**Comment by sampoder** [comment]
sorry

**Comment by sampoder** [comment]
btw this wouldn't have fixed it I think

**Comment by sampoder** [comment]
or I did it differently, anyways thank you for taking the time

**Comment by iamcpdev** [comment]
Lol yeah it wouldn't have. Wasn't paying attention.

**Comment by lachlanjc** [comment]
This isn't the issue; `public` is served at the root. The problem is it needs to serve them from summer.hackclub.com instead of hackclub.com

**Comment by iamcpdev** [comment]
Yep figured that out once I submitted the PR that's why I closed and deleted plus Sam took care of this already. ☺️

**Pull request closed without merging**
