### PR TITLE
Early Draft of Summer Scrapbook

### PR DESCRIPTION
**Pull request by sampoder**
I couldn't work out the other api so i just used airbender, it's kind of a mess

### CODE REVIEW

**Comment by lachlanjc** [comment]
Thank you so much for getting started on this! I’ll take a design/code pass a little later today.

**Comment by sampoder** [comment]
these are the current issues:

not filtering the non images and design needs work on in general

**Comment by sampoder** [comment]
New known issues:

We have all images but it seems that going from props to display isn't working

Design stuff again

**Comment by sampoder** [comment]
We part ways code, very interesting, very bulky and very much disappearing

bye bye

**Pull request closed without merging**
